### ISSUE TITLE
[WIP] Roadmap to version 1.0.0

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#236]
- [x] add image saving (downloading) #148 #135 
- [x] 2D slice zooming #56 
- [x] 2D slice panning #57 
- [x] flip clip plane #70 
- [x] make clip plane draggable #71 
- [x] ~url pasting when canvas has focus #130~
- [x] emit events when loading images #142 
- [x] ~add grow cut features #147~
- [x] emit intensity range events when selection box is finished #172 
- [x] image loading in various use cases #149 
- [x] basic UI interactions on desktop and touch screen devices #268 
- [x] niimath WASM integration
- [x] document javascript functions

**Comment by hanayik** [comment]
url pasting from the clipboard seems to have some security related difficulties, and therefore is getting deferred to a later version since it's not a must-have feature anyways.

**Comment by hanayik** [comment]
grow cut is being deferred to a later release, but basic drawing tools have been added to niivue. see #313
