### ISSUE TITLE
[WIP] Roadmap to version 2.0.0

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#237]
- [x] ~WebGPU #79~
- [x] ~switch to typescript #141~
- [x] ~add grow cut features #147~
- [x] ~real-time interaction #175~
- [x] ~report descriptive stats for images #140~ 
- [x] ~add drawing interactions #103~ 
- [x] ~add Apple Pencil support on iPad #114~
- [x] ~4D data viewing support #65~ 
- [x] ~integration with openneuro.org #134~ 
- [x] ~load PNG images #144~
- [x] ~VOI creation (drawing) #178~
- [x] ~easy masking #174~
- [x] ~cutout coloring options #177~ 
- [x] ~mosaic view as in MRIcroGL (or "Lightbox" in FSLeyes)~

**Comment by hanayik** [comment]
@neurolabusc, we have accomplished nearly all of the items here (including those from our v1.0.0 list). I suggest that we:

1. update gzip to in nifti-reader-js to use fflate
2. release new nifti-reader-js
3. include new nifti-reader-js in niivue
4. release new version of niivue and set that version to 1.0.0

**Comment by alexisthual** [comment]
Can't wait to see the typescript version of this repo :blush:

**Comment by hanayik** [comment]
@alexisthual, it would be nice, but it's a long way off. @cdrake has done some work adding in types via JSdoc comments, but that's about it so far. Will keep it on the list though!

**Comment by hanayik** [comment]
@neurolabusc , and @cdrake, 

I'm inclined to release NiiVue 1.0.0 once we merge in the updated nifti-reader-js with enhanced zip/unzip libs. 

Any thoughts?

**Comment by neurolabusc** [comment]
I think version 1 means we are beyond the break fast point and are hardening the API. I do think our regression testing is pretty good. The  one hesitation is whether the new collaborations with nilearn, FreeSurfer, DSI studio and MRtrix teams influence this. It might be worth leveraging their collective wisdom and use cases to refine our API. Due to this, I would defer a 1.0 release a bit.

**Comment by alexisthual** [comment]
I can't speak for the whole team obviously, but my feeling is that nilearn / scikit-learn people are rather conservative regarding releases haha (scikit 1.0 was only released one year ago, nilearn is still at 0.10).

My gut feeling is that integrating niivue with other pieces of software will indeed be a very good stress-test for the current API.
It also feels to me that using typescript before releasing 1.0 would be an other sensible stress-test.
After that, I guess there will be enough clear use-cases and examples that the API can be considered somewhat stable.

**Comment by alexisthual** [comment]
Also, you must hear that often, but I think that the package's name is unfortunately very confusing.
I think that a significant proportion of users might not realise right away that it's not only meant for `vue` developers.

If you think it is ever going to change, then the sooner is probably the better :smile: 
Maybe something like `niiview`, `niiengine`, `niirender` would work? I know people (myself included) can get very emotionally attached to a product's name and that changing in the middle of the road is hard anyways...
